[package]
name = "shade"
version = "0.1.0"
authors = ["Christer Sandberg <chrsan@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[dev-dependencies]
png = "0.16"
structopt = "0.3"
